SHELL=bash

include .make/Makefile

vignettes/startup-intro.md: OVERVIEW.md vignettes/incl/clean.css
	sed -i '/%\\Vignette/!d' $@
	echo "<!-- DO NOT EDIT THIS FILE! Edit 'OVERVIEW.md' instead and then rebuild this file with 'make vigs' -->" >> $@
	cat $< >> $@

vigs: vignettes/startup-intro.md


bioc-update: inst/bioc-3.11 inst/bioc-3.12

inst/bioc-%: FORCE
	mkdir -p "$@"
	bioc_version=$(@F); \
	bioc_version=$${bioc_version/bioc-/}; \
	echo "bioc_version=$$bioc_version"; \
	cd "$@"; \
	curl -L -o check.Renviron https://raw.githubusercontent.com/Bioconductor/BBS/master/$$bioc_version/Renviron.bioc
	ls -l "$@"

FORCE:
